spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dbURL}
    username: ${dbUsername:root}
    password: ${dbPassword}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

